//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseExplorer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<DbExplorer_GetTablesAndColumns_Result> DbExplorer_GetTablesAndColumns()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DbExplorer_GetTablesAndColumns_Result>("DbExplorer_GetTablesAndColumns");
        }
    
        public virtual ObjectResult<DbExplorer_GetAssociatedDataSets_Result> DbExplorer_GetAssociatedDataSets(string tableName, string columnName, Nullable<int> id)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            var columnNameParameter = columnName != null ?
                new ObjectParameter("columnName", columnName) :
                new ObjectParameter("columnName", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DbExplorer_GetAssociatedDataSets_Result>("DbExplorer_GetAssociatedDataSets", tableNameParameter, columnNameParameter, idParameter);
        }
    }
}
